name: Update products.json from Premiere (Playwright)

on:
  schedule:
    - cron: "0 2 * * *"   # daily at 02:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-products:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          PREMIERE_STORE_BASE: ${{ secrets.PREMIERE_STORE_BASE }}
          DEBUG_SCRAPER: "1"
        run: node scripts/scrapePremiere.mjs

      - name: Upload debug artifacts (HTML & screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: premiere-debug
          path: |
            debug/**
            products.json
          if-no-files-found: ignore

      - name: Commit & push (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add products.json || true
          git commit -m "chore: daily products.json refresh [skip ci]" || echo "No changes to commit"
          git push
